# Generated by Django 3.0.8 on 2021-01-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_inventario', '0002_remove_productos_inventarios_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos_inventarios',
            old_name='contenido',
            new_name='descripcion',
        ),
    ]
