# Generated by Django 3.0.8 on 2021-01-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_inventario', '0003_auto_20210121_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_inventarios',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
