# Generated by Django 3.0.8 on 2021-01-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_inventario', '0004_auto_20210121_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_inventarios',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
