# Generated by Django 3.1.5 on 2021-01-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
